server:
  port: 8080

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

app:
  jwt:
    secret: h9MzEb9WR6kz5Lhz8McrHzBCn0Z7E9nsOdfUZ3C48mA=
